corner-radius = 12;
rounded-corners-exclude = ["class_g = 'Polybar'", "window_type = 'tooltip'"];
backend = "glx";
blur: { method = "dual_kawase"; strength = 6; background = false; background-frame = false; background-fixed = false; }
shadow = true; shadow-radius = 15; shadow-opacity = 0.4; shadow-offset-x = -15; shadow-offset-y = -15; shadow-color = "#000000";
vsync = true; use-damage = true; glx-no-stencil = true;
fading = true; fade-in-step = 0.03; fade-out-step = 0.03; fade-delta = 4;
animations = true; animation-stiffness = 110.0; animation-dampening = 20.0; animation-clamping = true; animation-mass = 1.0;
animation-for-open-window = "zoom"; animation-for-unmap-window = "zoom"; animation-for-workspace-switch-in = "slide-down"; animation-for-workspace-switch-out = "slide-up";
