[General]
Background="Backgrounds/tokyo-night-celestial.png"
Blur=true
BlurRadius=60
CornerRadius=24
PopupBackground="#991a1b26"
UserColor="#c0caf5"
PasswordColor="#c0caf5"
HighlightColor="#7aa2f7"
HoverColor="#8db0f8"
ErrorColor="#f7768e"
Font="JetBrainsMono Nerd Font"
FontSize=11
PositionX=center
PositionY=center
